
print(1 + 2)
print(6 - 4)
print(3 * 5)
print(9 / 3)
print(3 ** 2)
print(5 % 3)
print(4  ** .5)
print('e' * 2)
print('e' + str(2))
print(int(3.5))
print(float(1))
a =(int(input('введите 1 число: ')))
b =(int(input('введите 2 число: ')))
print(a + b, a - b, a * b, a / b)
print(id(a), id(b))
